import Head from "next/head";

import { useUser, SignInButton, UserButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();
  if (!user) return null;
  return (
    <div className="flex w-full gap-3">
      <img
        className="h-16 w-16 rounded-full"
        src={user.imageUrl}
        alt="users profile image"
      />
      <input
        placeholder="Type some emojis!"
        className="grow bg-transparent outline-none"
        type="text"
      />
    </div>
  );
};

export default function Home() {
  //curremy user?
  const user = useUser();

  const { data } = api.post.getAll.useQuery();

  // if (isLoading) return <div>loading..</div>;
  if (!data) return <div>something went wrong i guess..</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="h-screen w-full border-x  border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && CreatePostWizard()}
            {user.isSignedIn && <UserButton />}
          </div>

          <div className="flex flex-col">
            {[...data, ...data]?.map(({ post, author }) => (
              <div key={post.id} className="border-slate-4 border-b p-8">
                {post.content}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
