import Head from "next/head";

import { useUser, SignInButton, UserButton } from "@clerk/nextjs";

import { api, RouterOutputs } from "~/utils/api";
//!!!!!!!!!!!!!
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();
  if (!user) return null;
  return (
    <div className="flex w-full gap-3">
      <img
        className="h-16 w-16 rounded-full"
        src={user.imageUrl}
        alt="users profile image"
      />
      <input
        placeholder="Type some emojis!"
        className="grow bg-transparent outline-none"
        type="text"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["post"]["getAll"][number];

const Postview = (props: PostWithUser) => {
  const { post, author } = props;

  return (
    <div key={post.id} className="flex gap-3 border-b border-slate-400 p-4">
      <img src={author.imageUrl} className="h-14 w-14 rounded-full" />
      <div className="flex flex-col">
        <div className="flex gap-1  font-bold ">
          <span className="text-slate-300">{`@${author.username}`}</span>
          <span className="font-thin text-gray-400 antialiased">{`· ${dayjs(
            post.createdAt,
          ).fromNow()}`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
};

export default function Home() {
  const user = useUser();

  const { data } = api.post.getAll.useQuery();

  if (!data) return <div>something went wrong i guess..</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="h-screen w-full border-x  border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && CreatePostWizard()}
            {user.isSignedIn && <UserButton />}
          </div>

          <div className="flex flex-col">
            {[...data, ...data]?.map((fullPost) => (
              <Postview {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
