name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # That's correct. You should not include your GitHub Actions workflow YAML files in your .gitignore file, as GitHub relies on these workflow files to configure and run your CI/CD processes. Excluding them from version control would prevent GitHub from executing the workflows.

  # ამიტომ არ მაქ აქ ნამდვილი db url
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript Type Checking
        run: npm run typecheck

      - name: Run ESLint
        run: npm run lint
