name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATABASE_URL: ${{ 'mysql://b89t854c1crm175t131s:pscale_pw_oN6oKbYPdFn8CTotxI8Ee99532Ttw59JhfbW6xxqoZZ@aws.connect.psdb.cloud/t3-db?sslaccept=strict' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript Type Checking
        run: npm run typecheck

      - name: Run ESLint
        run: npm run lint
